spring.application.name=chat-app
spring.datasource.url=jdbc:mysql://localhost:3306/chatingApp
spring.datasource.username=root
spring.datasource.password=anm@#$19
spring.jpa.hibernate.ddl-auto=update

